name: Master Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Activate Service Account
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        run: |
          echo "$GCLOUD_AUTH" | base64 --decode > "$HOME"/gcloud.json
          sh -c "gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build React app
        run: npm run build
      #    - name: Deploy to gh-pages
      #      uses: peaceiris/actions-gh-pages@v3
      #      with:
      #        github_token: ${{ secrets.GITHUB_TOKEN }}
      #        publish_dir: ./build
      - name: Deploy to Google App
        run: |
          gcloud app deploy --project yellow-notes-wtf
      - name: Updating Domain
        run: echo "Update enviroment"
